version: "3"
services:
    web:
        build: ./QuizEngineBackend/QuizServer
        # ports:
        #     - "8010:80"
        depends_on:
            - db
        # network_mode: potentiometer
        expose:
            - "80"
        labels:
            - "SERVICE_NAME=QuizEngine"
            - "SERVICE_TAGS=QuizEngineTag"
    db:
        image: "mongo:latest"
        # ports:
        #     - "9007:27017"
        # network_mode: potentiometer
