version: "3"
services:
    web:
        container_name: docker-mongo-QuizEngine
        build: ./QuizServer .
        ports:
            - "8010:80"
        depends_on:
            - db
    db:
        container_name: quizenginemongo
        image: "mongo:latest"
        ports:
            - "9007:27017"
